# Generated by Django 5.2.3 on 2025-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='id_professor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
