# Generated by Django 5.2.3 on 2025-06-17 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('study_cycle', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('credits', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('duration_weeks', models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(20)])),
                ('theory_hours', models.PositiveSmallIntegerField()),
                ('practice_hours', models.PositiveSmallIntegerField()),
                ('study_plan', models.PositiveSmallIntegerField(choices=[(2014, '2001'), (2019, '2015'), (2025, '2019')])),
                ('subject_code', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
