# Generated by Django 5.2.3 on 2025-06-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='practice_hours',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='theory_hours',
            field=models.PositiveSmallIntegerField(blank=True, default=''),
        ),
    ]
