# Generated by Django 5.2.3 on 2025-06-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_course_practice_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='practice_hours',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='theory_hours',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name', 'study_plan'), name='unique_course_per_study_plan'),
        ),
    ]
