# Generated by Django 5.2.3 on 2025-06-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_course_study_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Electivo', 'Electivo'), ('Obligatorio', 'Obligatorio')], default='Obligatorio'),
        ),
        migrations.AddField(
            model_name='course',
            name='professional_career',
            field=models.CharField(choices=[('Igeniería Informática', 'Igeniería Informática'), ('Igeniería de Telecomunicaciones', 'Igeniería de Telecomunicaciones'), ('Igeniería Mecatrónica', 'Igeniería Mecatrónica'), ('Igeniería Eléctrica', 'Igeniería Eléctrica')], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='study_type',
            field=models.CharField(choices=[('Especialidad', 'Especialidad'), ('Específico', 'Específico'), ('General', 'General')], default='Especialidad'),
        ),
        migrations.AlterField(
            model_name='course',
            name='study_plan',
            field=models.PositiveSmallIntegerField(choices=[(2001, 2001), (2015, 2015), (2019, 2019)]),
        ),
    ]
