# Generated by Django 5.2.3 on 2025-06-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_course_professional_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professional_career',
        ),
    ]
