# Generated by Django 5.2.3 on 2025-06-17 22:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_course_professional_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenCourse',
            fields=[
                ('id_open_course', models.AutoField(primary_key=True, serialize=False)),
                ('start_class', models.DateTimeField()),
                ('end_class', models.DateTimeField()),
                ('academic_year', models.PositiveSmallIntegerField(default=2025)),
                ('academic_semester', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('professional_career', models.CharField(choices=[('Ingeniería Informática', 'Ingeniería Informática'), ('Ingeniería de Telecomunicaciones', 'Ingeniería de Telecomunicaciones'), ('Ingeniería Electrónica', 'Ingeniería Electrónica'), ('Ingeniería Mecatrónica', 'Ingeniería Mecatrónica')])),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_courses', to='api.professor')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_courses', to='api.student')),
            ],
            options={
                'verbose_name': 'OpenCourse',
                'verbose_name_plural': 'OpenCourses',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_schedule', models.AutoField(primary_key=True, serialize=False)),
                ('day_week', models.CharField(choices=[('Lunes', 0), ('Martes', 1), ('Miércoles', 1), ('Jueves', 1), ('Viernes', 1), ('Sábado', 1), ('Domingo', 1)])),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_open_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.opencourse')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
