# Generated by Django 5.2.3 on 2025-06-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_opencourse_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opencourse',
            name='id_student',
        ),
    ]
