# Generated by Django 5.2.3 on 2025-06-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_opencourse_id_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opencourse',
            name='end_class',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='start_class',
            field=models.TimeField(),
        ),
    ]
