# Generated by Django 5.2.3 on 2025-06-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_opencourse_id_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_week',
            field=models.CharField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
    ]
