# Generated by Django 5.2.3 on 2025-06-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_schedule_day_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opencourse',
            name='end_class',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='start_class',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_week',
            field=models.SmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
    ]
