# Generated by Django 5.2.3 on 2025-06-30 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_opencourse_end_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollStudent',
            fields=[
                ('id_enroll_student', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_open_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.opencourse')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'verbose_name': 'EnrollStudent',
                'verbose_name_plural': 'EnrollStudents',
            },
        ),
    ]
