# Generated by Django 5.2.3 on 2025-07-02 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_enrollstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id_attendance', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('attendance', models.SmallIntegerField(choices=[(0, 'Presente'), (1, 'Ausente'), (2, 'Tardanza')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_enroll_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enrollstudent')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
    ]
