# Generated by Django 5.2.3 on 2025-07-04 04:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('type_note', models.CharField(choices=[('Evaluación Parcial', 'Evaluación Parcial'), ('Evaluación Final', 'Evaluación Final'), ('Trabajos Académicos', 'Trabajos Académicos')], default='Examen')),
                ('note', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_enroll_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enrollstudent')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
