# Generated by Django 5.2.2 on 2025-07-09 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='career',
            field=models.CharField(choices=[('Ingeniería Informática', 'Ingeniería Informática'), ('Ingeniería de Telecomunicaciones', 'Ingeniería de Telecomunicaciones'), ('Ingeniería Electrónica', 'Ingeniería Electrónica'), ('Ingeniería Mecatrónica', 'Ingeniería Mecatrónica')], default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year_admission',
            field=models.PositiveSmallIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
            preserve_default=False,
        ),
    ]
